services:
  db:
    image: postgres
    restart: always
    volumes:
      - db_volume:/data:rw
  backend:
    build: .
    ports: 
      - "3000:3000"

volumes:
  db_volume:
    driver: local
    driver_opts:
      o: "size=100m, uid=1000"
      device: tmpfs
      type: tmpfs